Repository eventlet/eventlet, pull requests merged in 2023-12, with the labels that each got.

#845 Automatize and modernize deployments
  .github/workflows/publish.yml
  bin/release
  eventlet/__init__.py
  pyproject.toml
  setup.py
Labels: release, infra

#847 Fix Python 3.13 compat by adding missing attibute '_is_main_interpreter'
  NEWS
  eventlet/green/thread.py
Labels: Python3.13_compat, important, urgent, bug

#754 py<=3.10: Green logging locks
  eventlet/patcher.py
  tests/isolated/patcher_existing_logging_module_lock.py
  tests/patcher_test.py
Labels: important, bug

#811 Fix memory leak in module greendns (alternative to #682)
  eventlet/support/greendns.py
  tests/greendns_test.py
Labels: important, bug

#796 Update ssl.py
  eventlet/green/ssl.py
Labels: feature-tls

#853 Drop old code based on python < 3.7, part 1: eventlet directory
  eventlet/__init__.py
  eventlet/backdoor.py
  eventlet/convenience.py
  eventlet/corolocal.py
  eventlet/coros.py
  eventlet/dagpool.py
  eventlet/db_pool.py
  eventlet/debug.py
  eventlet/event.py
  eventlet/green/BaseHTTPServer.py
  eventlet/green/MySQLdb.py
  eventlet/green/Queue.py
  eventlet/green/SocketServer.py
  eventlet/green/builtin.py
  eventlet/green/http/__init__.py
  eventlet/green/http/client.py
  eventlet/green/http/cookiejar.py
  eventlet/green/http/cookies.py
  eventlet/green/httplib.py
  eventlet/green/os.py
  eventlet/green/profile.py
  eventlet/green/select.py
  eventlet/green/ssl.py
  eventlet/green/subprocess.py
  eventlet/green/thread.py
  eventlet/green/threading.py
  eventlet/green/urllib/__init__.py
  eventlet/green/zmq.py
  eventlet/greenio/__init__.py
  eventlet/greenio/base.py
  eventlet/greenio/py2.py
  eventlet/greenio/py3.py
  eventlet/greenpool.py
  eventlet/greenthread.py
  eventlet/hubs/__init__.py
  eventlet/hubs/epolls.py
  eventlet/hubs/hub.py
  eventlet/hubs/kqueue.py
  eventlet/hubs/poll.py
  eventlet/hubs/selects.py
  eventlet/hubs/timer.py
  eventlet/patcher.py
  eventlet/pools.py
  eventlet/queue.py
  eventlet/semaphore.py
  eventlet/support/greendns.py
  eventlet/support/stacklesss.py
  eventlet/tpool.py
  eventlet/websocket.py
  eventlet/wsgi.py
  eventlet/zipkin/api.py
  eventlet/zipkin/client.py
  eventlet/zipkin/http.py
  eventlet/zipkin/wsgi.py
Labels: important, deprecation
