Repository eventlet/eventlet, pull requests merged in 2024-01, with the labels that each got.

#826 Fix security issue related to RFC 9112
  NEWS
  eventlet/wsgi.py
  tests/wsgi_test.py
Labels: important, urgent, security

#882 Reword maintenance policy sentences
  README.rst
  doc/index.rst
Labels: doc

#880 Modernize doc generation
  .github/workflows/docs.yaml
  .github/workflows/publish.yaml
  .gitignore
  .readthedocs.yaml
  bin/build-website.bash
  doc/Makefile
  doc/authors.rst
  doc/make.bat
  doc/requirements.txt
  doc/source/_templates/layout.html
  doc/source/authors.rst
  doc/source/basic_usage.rst
  doc/source/common.txt
  doc/source/conf.py
  doc/source/design_patterns.rst
  doc/source/environment.rst
  doc/source/examples.rst
  doc/source/history.rst
  doc/source/hubs.rst
  doc/source/images/threading_illustration.png
  doc/source/index.rst
  doc/source/modules.rst
  doc/source/modules/backdoor.rst
  doc/source/modules/corolocal.rst
  doc/source/modules/dagpool.rst
  doc/source/modules/db_pool.rst
  doc/source/modules/debug.rst
  doc/source/modules/event.rst
  doc/source/modules/greenpool.rst
  doc/source/modules/greenthread.rst
  doc/source/modules/pools.rst
  doc/source/modules/queue.rst
  doc/source/modules/semaphore.rst
  doc/source/modules/timeout.rst
  doc/source/modules/websocket.rst
  doc/source/modules/wsgi.rst
  doc/source/modules/zmq.rst
  doc/source/patching.rst
  doc/source/real_index.html
  doc/source/reference/api/eventlet.green.OpenSSL.rst
  doc/source/reference/api/eventlet.green.http.rst
  doc/source/reference/api/eventlet.green.rst
  doc/source/reference/api/eventlet.green.urllib.rst
  doc/source/reference/api/eventlet.greenio.rst
  doc/source/reference/api/eventlet.hubs.rst
  doc/source/reference/api/eventlet.rst
  doc/source/reference/api/eventlet.support.rst
  doc/source/reference/api/eventlet.zipkin.rst
  doc/source/reference/api/modules.rst
  doc/source/ssl.rst
  doc/source/testing.rst
  doc/source/threading.rst
  doc/source/zeromq.rst
  eventlet/green/zmq.py
  eventlet/hubs/__init__.py
  tox.ini
Labels: infra, doc

#888 fix bad directory name in readthedocs config file
  .readthedocs.yaml
Labels: bug, doc

#886 Asyncio hub support for Python 3.7 to 3.9
  .github/workflows/test.yaml
  eventlet/hubs/asyncio.py
Labels: tests

#643 Extend test cert to 2049
  tests/test_server.crt
Labels: importance-enhancement, need-contributor, feature-tls

#884 Handle transport endpoint shutdown in conditions
  eventlet/websocket.py
  eventlet/wsgi.py
Labels: design

#789 fix truncate size can be None
  eventlet/greenio/py3.py
Labels: bug

#895 install eventlet at readthedocs build
  .readthedocs.yaml
Labels: bug, doc

#894 Add very minimal linting
  .github/workflows/style.yaml
  .gitignore
  eventlet/backdoor.py
  eventlet/greenio/py2.py
  eventlet/patcher.py
  eventlet/zipkin/api.py
  pyproject.toml
  tests/greenio_test.py
  tests/greenpool_test.py
  tests/isolated/patcher_builtin.py
  tests/parse_results.py
  tests/ssl_test.py
  tox.ini
Labels: tests, infra

#899 Move docs to readthedocs
  README.rst
  pyproject.toml
Labels: doc

#898 update changelog for version 0.35.0
  NEWS
Labels: release, changelog

#900 document our process
  doc/source/index.rst
  doc/source/maintenance/process.rst
Labels: doc

#903 clean remnant files
  .hgignore
  bin/build-website.bash
Labels: infra

#904 Add Python 3.7 to pyproject classifiers
  pyproject.toml
Labels: infra
